// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBL2m0VYGvC4REWWMg4p6k1sCESGfmZ8',
    appId: '1:955563430703:web:0120b01d9da6d9abcd47da',
    messagingSenderId: '955563430703',
    projectId: 'govunityconnect',
    authDomain: 'govunityconnect.firebaseapp.com',
    storageBucket: 'govunityconnect.appspot.com',
    measurementId: 'G-L1X2P6HE6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRE70KIDi6eXxwQ-bGQtg5LDdtoUUQjDE',
    appId: '1:955563430703:android:5526a547012c9ad3cd47da',
    messagingSenderId: '955563430703',
    projectId: 'govunityconnect',
    storageBucket: 'govunityconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvHxs-AQlXzoO5NIjvhrBd_IS-f1_UoU',
    appId: '1:955563430703:ios:b2ca70d1500ec643cd47da',
    messagingSenderId: '955563430703',
    projectId: 'govunityconnect',
    storageBucket: 'govunityconnect.appspot.com',
    iosBundleId: 'com.example.govunityConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHvHxs-AQlXzoO5NIjvhrBd_IS-f1_UoU',
    appId: '1:955563430703:ios:09c088c2f88e3e96cd47da',
    messagingSenderId: '955563430703',
    projectId: 'govunityconnect',
    storageBucket: 'govunityconnect.appspot.com',
    iosBundleId: 'com.example.govunityConnect.RunnerTests',
  );
}
