// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCptacwGj0c8JRFMrVxbosy-8Rw8tcFCoY',
    appId: '1:433084712854:web:39ddf5adf0dd2965f9bfb7',
    messagingSenderId: '433084712854',
    projectId: 'govschemeinformer',
    authDomain: 'govschemeinformer.firebaseapp.com',
    storageBucket: 'govschemeinformer.firebasestorage.app',
    measurementId: 'G-MFHH6W6MFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkJajIClIsRtw_E0hisHFfs0snVU2mzc',
    appId: '1:433084712854:android:58a0bf6a98cb7a82f9bfb7',
    messagingSenderId: '433084712854',
    projectId: 'govschemeinformer',
    storageBucket: 'govschemeinformer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhqneSz1c0EX2u8Xa70CC3O_O-9oW2U_Y',
    appId: '1:433084712854:ios:72a9d93bc7bbcbddf9bfb7',
    messagingSenderId: '433084712854',
    projectId: 'govschemeinformer',
    storageBucket: 'govschemeinformer.firebasestorage.app',
    iosBundleId: 'com.example.govunityConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhqneSz1c0EX2u8Xa70CC3O_O-9oW2U_Y',
    appId: '1:433084712854:ios:72a9d93bc7bbcbddf9bfb7',
    messagingSenderId: '433084712854',
    projectId: 'govschemeinformer',
    storageBucket: 'govschemeinformer.firebasestorage.app',
    iosBundleId: 'com.example.govunityConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCptacwGj0c8JRFMrVxbosy-8Rw8tcFCoY',
    appId: '1:433084712854:web:36a319eb215bc87af9bfb7',
    messagingSenderId: '433084712854',
    projectId: 'govschemeinformer',
    authDomain: 'govschemeinformer.firebaseapp.com',
    storageBucket: 'govschemeinformer.firebasestorage.app',
    measurementId: 'G-2PV2FE0386',
  );

}